RT_DRV_PATH := .
RT_DRV_NAME := mt7610e



obj-m += $(RT_DRV_NAME).o

$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mtd_bridge/ralink-flash.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_md5.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_sha2.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_hmac.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_aes.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_arc4.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_wep.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_wpa.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_tkip.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_aes.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/mlme.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/action.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ba_action.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_data.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_sync.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_sanity.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_info.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_cfg.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_profile.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_asic.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_cmd.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rtmp_init.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rtmp_init_inf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rtmp_timer.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rt_channel.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rt_os_util.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_radar.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/vht.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/spectrum.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/txpower.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/scan.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ps.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/uapsd.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_data_pci.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mac_pci.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/eeprom.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ee_flash.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ee_efuse.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ee_prom.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mgmt/mgmt_entrytb.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mgmt/mgmt_ht.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mgmt/mgmt_vht.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mac/rtmp_mac.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mac/ral_nmac.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mcu/mcu.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mcu/mcu_and.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/rlt_rf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/rlt_phy.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/rtmp_phy.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/rate_ctrl/ra_ctrl.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/rate_ctrl/alg_legacy.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/rate_ctrl/alg_grp.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_assoc.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_auth.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_connect.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_mlme.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_sanity.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_sync.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_wpa.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_data.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_autoChSel.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_qload.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_cfg.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/ap_ioctl.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_proc.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_linux.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_profile.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_main_dev.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_rbus_pci_drv.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_rbus_pci_util.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_pci_rbus.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/pci_main_dev.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/cfg80211.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/cfg80211drv.o

### MT7610E
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/chips/rtmp_chip.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/chips/rt65xx.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/chips/mt76x0.o
ifeq ($(CONFIG_RT_ATE),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ate/chips/rt6590_ate.o
endif

ifeq ($(CONFIG_RT_ATE),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ate/common/rt_ate.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ate/common/ate_pci.o
ifeq ($(CONFIG_RT_QA),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ate/common/rt_qa.o
endif
endif

ifeq ($(CONFIG_MT7610_AP_LED),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rt_led.o
endif

ifeq ($(CONFIG_MT7610_AP_WDS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_wds.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_wds_inf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/client_wds.o
endif

ifeq ($(CONFIG_MT7610_AP_MBSS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_mbss.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_mbss_inf.o
endif

ifeq ($(CONFIG_MT7610_AP_APCLI),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_apcli.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_apcli_inf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/apcli_assoc.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/apcli_auth.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/apcli_ctrl.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/apcli_sync.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mat.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mat_iparp.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mat_pppoe.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mat_ipv6.o
ifeq ($(CONFIG_MT7610_AP_MAC_REPEATER),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_repeater.o
endif
endif

ifeq ($(CONFIG_MT7610_AP_DLS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_dls.o
endif

ifeq ($(CONFIG_MT7610_AP_IDS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_ids.o
endif

ifeq ($(CONFIG_MT7610_AP_DFS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_dfs.o
endif

ifeq ($(CONFIG_MT7610_AP_CARRIER),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_cs.o
endif

ifeq ($(CONFIG_RT_WSC),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wsc.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wsc_tlv.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_dh.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wsc_ufd.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_biginteger.o
ifeq ($(CONFIG_RT_WSC_V2),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wsc_v2.o
endif
endif

ifeq ($(CONFIG_RT_WAPI),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wapi.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wapi_sms4.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wapi_crypt.o
endif

ifeq ($(CONFIG_RT_IGMP_SNOOP),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/igmp_snoop.o
endif

ifeq ($(CONFIG_RT_NETIF_BLOCK),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/netif_block.o
endif

ifeq ($(CONFIG_RT_VIDEO_TURBINE),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_video.o
endif

ifeq ($(CONFIG_RT_BAND_STEERING),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_band_steering.o
endif